### ISSUE TITLE
slice indices must be integers or Noe

### ISSUE THREAD

**Issue by qianwangn** [dhammack/DSB2017#5]
when I run your code,I got this error slice indices must be integers
detail:
--> 174 	voxel = img[z_start:z_end,y_start:y_end,x_start:x_end]
        voxel = undefined
        img = array([[[-2048, -2048, -2048, ..., -2048, -2048,... -2048, ..., -2048, -2048, -2048]]], dtype=int16)
        z_start = 68.5
        z_end = 81.5
        y_start = 268.5
        y_end = 311.5
        x_start = 75.5
        x_end = 118.5

build_luna_model_v29.py

**Comment by dhammack** [comment]
Are you using python3? 

I wrote this using python2. It seems that the issue is around line 300 in data_generator_fn.py. For python 3 you will need to wrap all divisions (e.g. x_center < numXpix/2) with int() calls, changing:

x_center < numXpix/2

to 

x_center < int(numXpix/2)

For example. This likely occurs many times in the data generation and perhaps in other places as well.

**Comment by johnlanbor** [comment]
Thanks  a lot 
but I still have another trouble
when i load your trained model,i got some error like :
ValueError: Improper config format: {u'l2': 9.999999747378752e-05, u'name': u'L1L2Regularizer', u'l1': 0.0}

already tried all the keras version,still cant load your model
